Convert to Python 3.x with the help of '2to3'
Additional changes include replacing `w.encode('ascii','replace')`
with `w` in `fast_file_path_to_list` as an argument to `intern`,
because in Python 3 `w` is `str`, not `bytes`, and `intern` requires
`str`.

Without the change running either `tversky_profile.py` or
`jaccard_profile.py` crashes with the following error message:

  TypeError: intern() argumet must be str, not bytes

Otherwise the change is simply the result of running

  $ 2to3 --write --nobackups .