tversky_ext_profile.py: Simplify convert_date()
Instead of going through the time.strptime() -> time.mktime() ->
datetime.fromtimestamp(), use datetime.strptime() directly.

Incidentally, this fixes the issue with revfinder's android.json
dataset, where the value of '1900-01-01 08:00:00.00000...' for
"grant_date" key in one of entries caused the script to crash
in convert_date() with the following error message:

```
Traceback (most recent call last):
  File ".\tversky_ext_profile.py", line 259, in <module>
    users = parse_file(f)
  File ".\tversky_ext_profile.py", line 164, in parse_file
    last_date = reviewers_last_date.get(hist['userId'], convert_date(hist['grant_date']) - timedelta(days=1))
  File ".\tversky_ext_profile.py", line 234, in convert_date
    return datetime.fromtimestamp(mktime(strptime(date_as_string[:-3], "%Y-%m-%d %H:%M:%S.%f")))
OverflowError: mktime argument out of range
```